
import { Inter, Josefin_Sans } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
// const josefin = Josefin_Sans({
//     weight: ['400', '500', '700'],
//     subsets: ['latin']
// })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col w-full h-[calc(100vh_-_5rem_-_1px)] bg-neutral-900`}>

                <main className='mt-20 w-full flex-grow px-10 mx-auto'>{children}</main>

                <Footer />
            </body>
        </html>
    )
}
